myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # new

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

posts/urls.py
"""Add Posts app url here"""
from django.urls import path
from .views import post_view, comment_view

app_name = 'posts'

urlpatterns = [
    path('', post_view.IndexView.as_view(), name='index'),
    path('<int:pk>/', post_view.DetailView.as_view(), name='detail'),
    path('<int:post_id>/test/', post_view.test, name='results'),
    path('<int:post_id>/comment', comment_view.comment, name='comment')
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

posts/models.py
"""Create your models here."""

from django.db import models

from django.utils.datetime_safe import datetime


class Category(models.Model):
    """Category Model"""

    title = models.CharField(max_length=30)

    def __str__(self):
        """Class to string"""
        return self.title


class Post(models.Model):
    """Post Model"""

    title = models.CharField(max_length=30)
    description = models.TextField()
    category = models.ManyToManyField(Category)
    post_image = models.ImageField(upload_to='pic_folder/', default='pic_folder/None/no-img.jpg')

    def __str__(self):
        """Class to string"""

        return self.title


class Comments(models.Model):
    """Comments Model"""

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    pub_date = models.DateTimeField(default=datetime.now)

    class Meta:
        """Comments Meta Model"""

        get_latest_by = 'pub_date'

    def __str__(self):
        """Class to string"""

        return self.text

posts/forms.py
"""
Add forms here
"""
from django.forms import ModelForm
from .models import Comments


class CommentForm(ModelForm):
    """
    Comment form template
    """

    class Meta:
        model = Comments
        fields = ['text']

posts/views/comment_view.py
"""
Comment
"""
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
# from django.views import generic
from ..models import Comments, Post


def comment(request, post_id):
    """Comment handler"""
    try:
        post = get_object_or_404(Post, pk=post_id)
    except (KeyError, Post.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'post': post,
            'error_message': "You didn't select a choice.",
        })
    else:
        Comments.objects.create(text=request.POST.get('text'), post_id=post_id)
        return HttpResponseRedirect(reverse('posts:detail', args=(post_id,)))

posts/views/post_view.py
# from django.shortcuts import render
"""Create your views here."""
from django.views import generic
from django.http import HttpResponse
from ..models import Post, Category


# Create your views here.

class IndexView(generic.ListView):  # pylint: disable=too-many-ancestors
    """Index view class"""

    template_name = 'posts/index.html'
    context_object_name = 'posts'
    paginate_by = '4'

    def get_queryset(self):
        """get_queryset"""
        # print(self.request.user.is_authenticated, 'user')
        category = self.request.GET.get('category', None)
        # data = []
        if category is None:
            data = Post.objects.all()
        else:
            data = Post.objects.filter(category=category)
        return data

    # def get_context_data(self, **kwargs):
    def get_context_data(self, *, object_list=None, **kwargs):
        """get_context_data"""
        context = super(IndexView, self).get_context_data(**kwargs, object_list=object_list)
        context['categories'] = Category.objects.all()
        return context


class DetailView(generic.DetailView):  # pylint: disable=too-many-ancestors
    """DetailView"""
    model = Post
    template_name = 'posts/blog-single.html'


def test(request, post_id):
    """test"""

    data = Post.objects.get(id=1).category.all()
    print(data)
    # cat = data.category.all()
    return HttpResponse(data)

posts/templates/posts/banner.html
 {% load static %}
 <section class="site-section pt-5 pb-5">
        <div class="container">
          <div class="row">
            <div class="col-md-12">

              <div class="owl-carousel owl-theme home-slider">
                <div>
                  <a href="blog-single.html" class="a-block d-flex align-items-center height-lg" style="background-image: url('{% static 'posts/images/img_1.jpg'%}'); ">
                    <div class="text half-to-full">
                      <span class="category mb-5">Food</span>
                      <div class="post-meta">
                        
                        <span class="author mr-2"><img src="{% static 'posts/images/person_1.jpg' %}" alt="Colorlib"> Colorlib</span>&bullet;
                        <span class="mr-2">March 15, 2018 </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        
                      </div>
                      <h3>How to Find the Video Games of Your Youth</h3>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem nobis, ut dicta eaque ipsa laudantium!</p>
                    </div>
                  </a>
                </div>
                <div>
                  <a href="blog-single.html" class="a-block d-flex align-items-center height-lg" style="background-image: url('{% static 'posts/images/img_2.jpg'%}'); ">
                    <div class="text half-to-full">
                      <span class="category mb-5">Travel</span>
                      <div class="post-meta">
                        
                        <span class="author mr-2"><img src="{% static 'posts/images/person_1.jpg' %}" alt="Colorlib"> Colorlib</span>&bullet;
                        <span class="mr-2">March 15, 2018 </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        
                      </div>
                      <h3>How to Find the Video Games of Your Youth</h3>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem nobis, ut dicta eaque ipsa laudantium!</p>
                    </div>
                  </a>
                </div>
                <div>
                  <a href="blog-single.html" class="a-block d-flex align-items-center height-lg" style="background-image: url('{% static 'posts/images/img_3.jpg'%}'); ">
                    <div class="text half-to-full">
                      <span class="category mb-5">Sports</span>
                      <div class="post-meta">
                        
                        <span class="author mr-2"><img src="{% static 'posts/images/person_1.jpg' %}" alt="Colorlib"> Colorlib</span>&bullet;
                        <span class="mr-2">March 15, 2018 </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                        
                      </div>
                      <h3>How to Find the Video Games of Your Youth</h3>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem nobis, ut dicta eaque ipsa laudantium!</p>
                    </div>
                  </a>
                </div>
              </div>
              
            </div>
          </div>
          
        </div>


      </section>

posts/templates/posts/blog-single.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    {% include './banner.html' %}

    <section class="site-section py-lg">
        <div class="container">

            <div class="row blog-entries element-animate">

                <div class="col-md-12 col-lg-8 main-content">
                    <img src="{{ post.post_image.url }}" alt="Image" class="img-fluid mb-5">
                    <div class="post-meta">
                        <span class="author mr-2"><img src="{% static 'posts/images/person_1.jpg' %}" alt="Colorlib"
                                                       class="mr-2"> Colorlib</span>&bullet;
                        <span class="mr-2">March 15, 2018 </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                    </div>
                    <h1 class="mb-4">{{ post.title }}</h1>
                    {% for category in post.category.all %}
                        <a class="category mb-5" href="#">{{ category }}</a>
                    {% endfor %}

                    <div class="post-content-body">
                        <p>{{ post.description }}</p>
                    </div>


                    <div class="pt-5">
                        <p>Categories:
                            {% for category in post.category.all %}
                                <a href="#">{{ category }}</a>
                            {% endfor %}
                        </p>
                    </div>


                    <div class="pt-5">
                        <h3 class="mb-5">6 Comments</h3>
                        <ul class="comment-list">
                            {% for comment in post.comments_set.all %}
                                <li class="comment">
                                    <div class="vcard">
                                        <img src="{% static 'posts/images/person_1.jpg' %}" alt="Image placeholder">
                                    </div>
                                    <div class="comment-body">
                                        <h3>Jean Doe</h3>
                                        <div class="meta">January 9, 2018 at 2:21pm</div>
                                        <p>{{ comment }}</p>
                                    </div>
                                </li>
                            {% endfor %}


                        </ul>
                        <!-- END comment-list -->
                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form method="POST" action="{% url 'posts:comment' post.id %}" class="p-5 bg-light">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    <input type="email" class="form-control" id="email">
                                </div>


                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea name="text" id="text" cols="30" rows="10"
                                              class="form-control"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn btn-primary">
                                </div>

                            </form>

                        </div>
                    </div>

                </div>

                <!-- END main-content -->


                <!-- END sidebar -->

            </div>
        </div>
    </section>


{% endblock %}

posts/templates/posts/footer.html
{% load static %}
<footer class="site-footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-4">
          <h3>About Us</h3>
          <p class="mb-4">
            <img src="{% static 'posts/images/img_1.jpg' %}" alt="Image placeholder" class="img-fluid">
          </p>

          <p>Lorem ipsum dolor sit amet sa ksal sk sa, consectetur adipisicing elit. Ipsa harum inventore reiciendis. <a href="#">Read More</a></p>
        </div>
        <div class="col-md-6 ml-auto">
{#          <div class="row">#}
{#            <div class="col-md-7">#}
{#              <h3>Latest Post</h3>#}
{#              <div class="post-entry-sidebar">#}
{#                <ul>#}
{#                  <li>#}
{#                    <a href="">#}
{#                      <img src="images/img_6.jpg" alt="Image placeholder" class="mr-4">#}
{#                      <div class="text">#}
{#                        <h4>How to Find the Video Games of Your Youth</h4>#}
{#                        <div class="post-meta">#}
{#                          <span class="mr-2">March 15, 2018 </span> &bullet;#}
{#                          <span class="ml-2"><span class="fa fa-comments"></span> 3</span>#}
{#                        </div>#}
{#                      </div>#}
{#                    </a>#}
{#                  </li>#}
{#                  <li>#}
{#                    <a href="">#}
{#                      <img src="images/img_3.jpg" alt="Image placeholder" class="mr-4">#}
{#                      <div class="text">#}
{#                        <h4>How to Find the Video Games of Your Youth</h4>#}
{#                        <div class="post-meta">#}
{#                          <span class="mr-2">March 15, 2018 </span> &bullet;#}
{#                          <span class="ml-2"><span class="fa fa-comments"></span> 3</span>#}
{#                        </div>#}
{#                      </div>#}
{#                    </a>#}
{#                  </li>#}
{#                  <li>#}
{#                    <a href="">#}
{#                      <img src="images/img_4.jpg" alt="Image placeholder" class="mr-4">#}
{#                      <div class="text">#}
{#                        <h4>How to Find the Video Games of Your Youth</h4>#}
{#                        <div class="post-meta">#}
{#                          <span class="mr-2">March 15, 2018 </span> &bullet;#}
{#                          <span class="ml-2"><span class="fa fa-comments"></span> 3</span>#}
{#                        </div>#}
{#                      </div>#}
{#                    </a>#}
{#                  </li>#}
{#                </ul>#}
{#              </div>#}
{#            </div>#}
{#            <div class="col-md-1"></div>#}
{#            #}
{#            <div class="col-md-4">#}
{##}
{#              <div class="mb-5">#}
{#                <h3>Quick Links</h3>#}
{#                <ul class="list-unstyled">#}
{#                  <li><a href="#">About Us</a></li>#}
{#                  <li><a href="#">Travel</a></li>#}
{#                  <li><a href="#">Adventure</a></li>#}
{#                  <li><a href="#">Courses</a></li>#}
{#                  <li><a href="#">Categories</a></li>#}
{#                </ul>#}
{#              </div>#}
{#              #}
{#              <div class="mb-5">#}
{#                <h3>Social</h3>#}
{#                <ul class="list-unstyled footer-social">#}
{#                  <li><a href="#"><span class="fa fa-twitter"></span> Twitter</a></li>#}
{#                  <li><a href="#"><span class="fa fa-facebook"></span> Facebook</a></li>#}
{#                  <li><a href="#"><span class="fa fa-instagram"></span> Instagram</a></li>#}
{#                  <li><a href="#"><span class="fa fa-vimeo"></span> Vimeo</a></li>#}
{#                  <li><a href="#"><span class="fa fa-youtube-play"></span> Youtube</a></li>#}
{#                  <li><a href="#"><span class="fa fa-snapchat"></span> Snapshot</a></li>#}
{#                </ul>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <p class="small">
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy; <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All Rights Reserved | This template is made with <i class="fa fa-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- END footer -->

posts/templates/posts/header.html
<header role="banner">
    <div class="top-bar">
      <div class="container">
        <div class="row">
          <div class="col-9 social">
            <a href="#"><span class="fa fa-twitter"></span></a>
            <a href="#"><span class="fa fa-facebook"></span></a>
            <a href="#"><span class="fa fa-instagram"></span></a>
            <a href="#"><span class="fa fa-youtube-play"></span></a>
          </div>
          <div class="col-3 search-top">
            <!-- <a href="#"><span class="fa fa-search"></span></a> -->
            <form action="#" class="search-top-form">
              <span class="icon fa fa-search"></span>
              <input type="text" id="s" placeholder="Type keyword to search...">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="container logo-wrap">
      <div class="row pt-5">
        <div class="col-12 text-center">
          <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
          <h1 class="site-logo"><a href="index.html">Wordify</a></h1>
        </div>
      </div>
    </div>
    
    <nav class="navbar navbar-expand-md  navbar-light bg-light">
      <div class="container">
        
       
        <div class="collapse navbar-collapse" id="navbarMenu">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link active" href="index.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Business</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="category.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Travel</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="category.html">Asia</a>
                <a class="dropdown-item" href="category.html">Europe</a>
                <a class="dropdown-item" href="category.html">Dubai</a>
                <a class="dropdown-item" href="category.html">Africa</a>
                <a class="dropdown-item" href="category.html">South America</a>
              </div>

            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="category.html" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
              <div class="dropdown-menu" aria-labelledby="dropdown05">
                <a class="dropdown-item" href="category.html">Lifestyle</a>
                <a class="dropdown-item" href="category.html">Food</a>
                <a class="dropdown-item" href="category.html">Adventure</a>
                <a class="dropdown-item" href="category.html">Travel</a>
                <a class="dropdown-item" href="category.html">Business</a>
              </div>

            </li>
            <li class="nav-item">
              <a class="nav-link" href="about.html">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.html">Contact</a>
            </li>
          </ul>
          
        </div>
      </div>
    </nav>
  </header>

posts/templates/posts/index.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    {% include './banner.html' %}
    <section class="site-section py-sm">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="mb-4">Latest Posts</h2>
                </div>
            </div>
            <div class="row blog-entries">
                <div class="col-md-12 col-lg-8 main-content">
                    <div class="row">
                        {% if posts %}
                            {% for post in  posts %}
                                <div class="col-md-6">
                                    <a href="{% url 'posts:detail' post.id %}" class="blog-entry element-animate"
                                       data-animate-effect="fadeIn">
                                        <img src="{{ post.post_image.url }}" alt="Image placeholder">
                                        <div class="blog-content-body">
                                            <div class="post-meta">
                                                <span class="author mr-2"><img
                                                        src="{% static 'posts/images/person_1.jpg' %}"
                                                        alt="Colorlib"> {{ post.title }}</span>&bullet;
                                                <span class="mr-2">March 15, 2018 </span> &bullet;
                                                <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                                            </div>
                                            <h2>{{ post.title }}</h2>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}

                            </div>
                            {% if is_paginated %}
                                <div class="pagination">
                                    <span class="page-links">
                                        {% if page_obj.has_previous %}
                                            <a href="/posts?page={{ page_obj.previous_page_number }}">previous</a>
                                        {% endif %}
                                        <span class="page-current">
                                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                        </span>
                                        {% if page_obj.has_next %}
                                            <a href="/posts?page={{ page_obj.next_page_number }}">next</a>
                                        {% endif %}
                                    </span>
                                </div>
                            {% endif %}
                        {% else %}
                            <p>No Posts found!!! :(</p>
                        {% endif %}

                </div>

                <!-- END main-content -->
                {% include './sidebar.html'  %}
                <!-- END sidebar -->

            </div>
        </div>
    </section>
{% endblock %}
  

posts/templates/posts/layout.html
<!doctype html>
{% load static %}
{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"> {% endcomment %}
<html lang="en">
  <head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300, 400,700|Inconsolata:400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'posts/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'posts/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'posts/fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'posts/css/style.css' %}">
  </head>
  <body>
    

    <div class="wrap">
   
        {% include './header.html' %}
            {% block content %}{% endblock %}
       {% include './footer.html' %}

    </div>
    
    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>
    <script src="{% static 'posts/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'posts/js/jquery-migrate-3.0.0.js' %}"></script>
    <script src="{% static 'posts/js/popper.min.js' %}"></script>
    <script src="{% static 'posts/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'posts/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'posts/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'posts/js/jquery.stellar.min.js' %}"></script>

    
    <script src="{% static 'posts/js/main.js'%}"></script>
  </body>
</html>

posts/templates/posts/sidebar.html
<div class="col-md-12 col-lg-4 sidebar">


    <div class="sidebar-box">
        <h3 class="heading">Categories</h3>
        <ul class="categories">
            {% for category in categories %}
                <li><a href="{% url 'posts:index' %}?category={{category.id}}">{{ category }} <span>(12)</span></a></li>
            {% endfor %}

        </ul>
    </div>
    <!-- END sidebar-box -->

    {#    <div class="sidebar-box">#}
    {#        <h3 class="heading">Tags</h3>#}
    {#        <ul class="tags">#}
    {##}
    {##}
    {#        </ul>#}
    {#    </div>#}
</div>